apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.labels.partOf }}
    platform-component: {{ .Values.labels.component }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
