---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.infra.postgres.configMap.name }}
  namespace: {{ .Values.infra.postgres.namespace }}
data:
  init-db.sql: |
{{ .Values.infra.postgres.configMap.initSQL | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.infra.postgres.service.name }}
  namespace: {{ .Values.infra.postgres.namespace }}
spec:
  selector:
    app: {{ .Values.infra.postgres.service.selector }}
  ports:
    - name: tcp-postgres
      port: {{ .Values.infra.postgres.service.port }}
      targetPort: {{ .Values.infra.postgres.service.targetPort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.infra.postgres.statefulSet.name }}
  namespace: {{ .Values.infra.postgres.namespace }}
spec:
  serviceName: {{ .Values.infra.postgres.statefulSet.serviceName }}
  replicas: {{ .Values.infra.postgres.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.infra.postgres.statefulSet.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.infra.postgres.statefulSet.selector }}
      annotations:
        sidecar.istio.io/inject: "{{ .Values.infra.postgres.statefulSet.sidecarInject }}"
    spec:
      enableServiceLinks: false
      containers:
        - name: postgres
          image: {{ .Values.infra.postgres.statefulSet.container.image }}
          ports:
            - containerPort: {{ .Values.infra.postgres.statefulSet.container.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.infra.postgres.secrets.user.name }}
                  key: {{ .Values.infra.postgres.secrets.user.key }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.infra.postgres.secrets.password.name }}
                  key: {{ .Values.infra.postgres.secrets.password.key }}
            - name: POSTGRES_DB
              value: {{ .Values.infra.postgres.statefulSet.container.db }}
            - name: PGDATA
              value: {{ .Values.infra.postgres.statefulSet.container.pgdata }}
          volumeMounts:
            - name: pgdata
              mountPath: {{ .Values.infra.postgres.statefulSet.container.mountPath }}
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: {{ .Values.infra.postgres.statefulSet.resources.requests.cpu }}
              memory: {{ .Values.infra.postgres.statefulSet.resources.requests.memory }}
            limits:
              cpu: {{ .Values.infra.postgres.statefulSet.resources.limits.cpu }}
              memory: {{ .Values.infra.postgres.statefulSet.resources.limits.memory }}
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.infra.postgres.statefulSet.container.dbUser }}", "-d", "{{ .Values.infra.postgres.statefulSet.container.db }}"]
            failureThreshold: {{ .Values.infra.postgres.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.infra.postgres.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.infra.postgres.probes.startup.timeoutSeconds }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.infra.postgres.statefulSet.container.dbUser }}", "-d", "{{ .Values.infra.postgres.statefulSet.container.db }}"]
            periodSeconds: {{ .Values.infra.postgres.probes.readiness.periodSeconds }}
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.infra.postgres.statefulSet.container.dbUser }}", "-d", "{{ .Values.infra.postgres.statefulSet.container.db }}"]
            periodSeconds: {{ .Values.infra.postgres.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.infra.postgres.probes.liveness.failureThreshold }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ .Values.infra.postgres.configMap.name }}
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.infra.postgres.statefulSet.volume.storage }}
