---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.infra.redis.service.name }}
  namespace: {{ .Values.infra.redis.namespace }}
spec:
  selector:
    app: {{ .Values.infra.redis.service.selector }}
  ports:
    - name: tcp-redis
      port: {{ .Values.infra.redis.service.port }}
      targetPort: {{ .Values.infra.redis.service.targetPort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.infra.redis.statefulSet.name }}
  namespace: {{ .Values.infra.redis.namespace }}
spec:
  serviceName: {{ .Values.infra.redis.statefulSet.serviceName }}
  replicas: {{ .Values.infra.redis.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.infra.redis.statefulSet.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.infra.redis.statefulSet.selector }}
      annotations:
        sidecar.istio.io/inject: "{{ .Values.infra.redis.statefulSet.sidecarInject }}"
    spec:
      enableServiceLinks: false
      containers:
        - name: redis
          image: {{ .Values.infra.redis.statefulSet.container.image }}
          command:
            - redis-server
            - --maxmemory
            - {{ .Values.infra.redis.statefulSet.container.maxMemory }}
            - --maxmemory-policy
            - {{ .Values.infra.redis.statefulSet.container.maxMemoryPolicy }}
            - --appendonly
            - "{{ .Values.infra.redis.statefulSet.container.appendOnly }}"
          ports:
            - containerPort: {{ .Values.infra.redis.statefulSet.container.port }}
          volumeMounts:
            - name: redisdata
              mountPath: {{ .Values.infra.redis.statefulSet.container.mountPath }}
          resources:
            requests:
              cpu: {{ .Values.infra.redis.statefulSet.resources.requests.cpu }}
              memory: {{ .Values.infra.redis.statefulSet.resources.requests.memory }}
            limits:
              cpu: {{ .Values.infra.redis.statefulSet.resources.limits.cpu }}
              memory: {{ .Values.infra.redis.statefulSet.resources.limits.memory }}
          startupProbe:
            exec:
              command: ["redis-cli", "ping"]
            failureThreshold: {{ .Values.infra.redis.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.infra.redis.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.infra.redis.probes.startup.timeoutSeconds }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: {{ .Values.infra.redis.probes.readiness.periodSeconds }}
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: {{ .Values.infra.redis.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.infra.redis.probes.liveness.failureThreshold }}
  volumeClaimTemplates:
    - metadata:
        name: redisdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.infra.redis.statefulSet.volume.storage }}
