apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.infra.redis.service.name }}
  namespace: {{ .Values.infra.redis.namespace }}
  labels:
    app: {{ .Values.infra.redis.service.selector }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.infra.redis.service.selector }}
  ports:
    - port: {{ .Values.infra.redis.service.port }}
      targetPort: {{ .Values.infra.redis.service.targetPort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.infra.redis.statefulSet.name }}
  namespace: {{ .Values.infra.redis.namespace }}
  labels:
    app: {{ .Values.infra.redis.statefulSet.selector }}
spec:
  serviceName: {{ .Values.infra.redis.statefulSet.serviceName }}
  replicas: {{ .Values.infra.redis.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.infra.redis.statefulSet.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.infra.redis.statefulSet.selector }}
        sidecar.istio.io/inject: {{ .Values.infra.redis.statefulSet.sidecarInject | quote }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.infra.redis.statefulSet.container.image }}
          ports:
            - containerPort: {{ .Values.infra.redis.statefulSet.container.port }}
          command:
            - redis-server
            - --appendonly
            - {{ .Values.infra.redis.statefulSet.container.appendOnly | quote }}
            - --maxmemory
            - {{ .Values.infra.redis.statefulSet.container.maxMemory | quote }}
            - --maxmemory-policy
            - {{ .Values.infra.redis.statefulSet.container.maxMemoryPolicy | quote }}
          volumeMounts:
            - name: redis-data
              mountPath: {{ .Values.infra.redis.statefulSet.container.mountPath }}
          resources:
            {{- toYaml .Values.infra.redis.statefulSet.container.resources | nindent 12 }}
          startupProbe:
            exec:
              command: ["redis-cli", "ping"]
            failureThreshold: {{ .Values.infra.redis.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.infra.redis.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.infra.redis.probes.startup.timeoutSeconds }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: {{ .Values.infra.redis.probes.readiness.periodSeconds }}
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: {{ .Values.infra.redis.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.infra.redis.probes.liveness.failureThreshold }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.infra.redis.statefulSet.container.resources.requests.memory | default "2Gi" }}


