apiVersion: batch/v1
kind: Job
metadata:
  name: seed-all
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
        - name: seed-all
          image: {{ .Values.imageRegistry }}{{ .Values.image.seedAll }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MILVUS_URI
              value: {{ .Values.milvus.uri | quote }}
            - name: TENANT_ID
              value: {{ .Values.tenantId | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.configMap }}
            - secretRef:
                name: {{ .Values.global.secret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


