{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: katonic-gateway
  namespace: {{ include "katonic.namespace" . }}
  labels:
    {{- include "katonic.labels" . | nindent 4 }}
spec:
  selector:
    app: istio-ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.global.domain | quote }}
        {{- if .Values.gateway.wildcardDomain }}
        - "*.{{ .Values.global.domain }}"
        {{- end }}
      {{- if .Values.gateway.httpsRedirect }}
      tls:
        httpsRedirect: true
      {{- end }}
    {{- if .Values.gateway.tls.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.global.domain | quote }}
        {{- if .Values.gateway.wildcardDomain }}
        - "*.{{ .Values.global.domain }}"
        {{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.gateway.tls.credentialName | default "katonic-tls" }}
    {{- end }}
{{- end }}
