replicas: 2
image: katonic/ace-bff
port: 3002
resources:
  requests: { cpu: 250m, memory: 256Mi }
  limits: { cpu: "1", memory: 512Mi }
websocket:
  pingInterval: 25000
  pingTimeout: 5000
  maxPayload: 1048576
