namespace: katonic-staging

images:

  adminApi: katonic/admin-api:staging
  agentApi: katonic/agent-api:staging
  agentRuntime: katonic/agent-runtime:staging
  aiGateway: katonic/ai-gateway:staging
  evalEngine: katonic/eval-engine:staging
  governanceProxy: katonic/governance-proxy:staging
  guardrailsEngine: katonic/guardrails-engine:staging
  knowledgeEngine: katonic/knowledge-engine:staging
  mcpGateway: katonic/mcp-gateway:staging
  modelDeploymentService: katonic/model-deployment-service:staging
  observability: katonic/observability:staging
  platformBackend: katonic/platform-backend:staging
  remoteConnections: katonic/remote-connections:staging
  workspaceService: katonic/workspace-service:staging

frontend:
  image: katonic/katonic-frontend:staging
