namespace: katonic-dev

images:

  adminApi: katonic/admin-api:dev
  agentApi: katonic/agent-api:dev
  agentRuntime: katonic/agent-runtime:dev
  aiGateway: katonic/ai-gateway:dev
  evalEngine: katonic/eval-engine:dev
  governanceProxy: katonic/governance-proxy:dev
  guardrailsEngine: katonic/guardrails-engine:dev
  knowledgeEngine: katonic/knowledge-engine:dev
  mcpGateway: katonic/mcp-gateway:dev
  modelDeploymentService: katonic/model-deployment-service:dev
  observability: katonic/observability:dev
  platformBackend: katonic/platform-backend:dev
  remoteConnections: katonic/remote-connections:dev
  workspaceService: katonic/workspace-service:dev

frontend:
  image: katonic/katonic-frontend:dev
