namespace: katonic

images:

  adminApi: katonic/admin-api:prod
  agentApi: katonic/agent-api:prod
  agentRuntime: katonic/agent-runtime:prod
  aiGateway: katonic/ai-gateway:prod
  evalEngine: katonic/eval-engine:prod
  governanceProxy: katonic/governance-proxy:prod
  guardrailsEngine: katonic/guardrails-engine:prod
  knowledgeEngine: katonic/knowledge-engine:prod
  mcpGateway: katonic/mcp-gateway:prod
  modelDeploymentService: katonic/model-deployment-service:prod
  observability: katonic/observability:prod
  platformBackend: katonic/platform-backend:prod
  remoteConnections: katonic/remote-connections:prod
  workspaceService: katonic/workspace-service:prod

frontend:
  image: katonic/katonic-frontend:prod
