apiVersion: v1
kind: Service
metadata:
  name: model-deployment
  namespace: {{ include "katonic.namespace" $ }}
  labels:
    app.kubernetes.io/name: model-deployment
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: model-deployment
