{{- range .Values.allowAllApps }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ .name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .app }}
  action: ALLOW
  rules:
    - {}
{{- end }}


