---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            paths: {{ toYaml .Values.jwtPublicPaths | nindent 14 }}
    - from:
        - source:
            requestPrincipals: ["*"]
{{- range .Values.allowAllApps }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .app }}
  action: ALLOW
  rules:
    - {}
{{- end }}
