{{- range .Values.destinationRules }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  host: {{ .host }}
  trafficPolicy:
    tls:
      mode: {{ .tlsMode }}
    {{- if or .connectionPool .outlierDetection }}
    {{- if .connectionPool }}
    connectionPool:
      {{- if .connectionPool.http }}
      http:
        {{- if .connectionPool.http.maxRequestsPerConnection }}
        maxRequestsPerConnection: {{ .connectionPool.http.maxRequestsPerConnection }}
        {{- end }}
        {{- if .connectionPool.http.idleTimeout }}
        idleTimeout: {{ .connectionPool.http.idleTimeout }}
        {{- end }}
      {{- end }}
      {{- if .connectionPool.tcp }}
      tcp:
        {{- if .connectionPool.tcp.maxConnections }}
        maxConnections: {{ .connectionPool.tcp.maxConnections }}
        {{- end }}
        {{- if .connectionPool.tcp.connectTimeout }}
        connectTimeout: {{ .connectionPool.tcp.connectTimeout }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if .outlierDetection }}
    outlierDetection:
      consecutive5xxErrors: {{ .outlierDetection.consecutive5xxErrors }}
      interval: {{ .outlierDetection.interval }}
      baseEjectionTime: {{ .outlierDetection.baseEjectionTime }}
      maxEjectionPercent: {{ .outlierDetection.maxEjectionPercent }}
    {{- end }}
    {{- end }}
{{- end }}


