{{- range .Values.destinationRules }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  host: {{ .host }}.{{ $.Values.namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: {{ .tlsMode }}
    {{- if .connectionPool }}
    connectionPool:
      http:
        h2UpgradePolicy: DEFAULT
        maxRequestsPerConnection: {{ .connectionPool.http.maxRequestsPerConnection }}
        {{- if .connectionPool.http.idleTimeout }}
        idleTimeout: {{ .connectionPool.http.idleTimeout }}
        {{- end }}
      tcp:
        maxConnections: {{ .connectionPool.tcp.maxConnections }}
        {{- if .connectionPool.tcp.connectTimeout }}
        connectTimeout: {{ .connectionPool.tcp.connectTimeout }}
        {{- end }}
    {{- end }}
    {{- if .outlierDetection }}
    outlierDetection:
      consecutive5xxErrors: {{ .outlierDetection.consecutive5xxErrors }}
      interval: {{ .outlierDetection.interval }}
      baseEjectionTime: {{ .outlierDetection.baseEjectionTime }}
      maxEjectionPercent: {{ .outlierDetection.maxEjectionPercent }}
    {{- end }}
{{- end }}
