apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.peerAuth[0].name }}
  namespace: {{ .Values.peerAuth[0].namespace }}
spec:
  mtls:
    mode: {{ .Values.peerAuth[0].mtlsMode }}
---
{{- range $i, $auth := .Values.peerAuth }}
{{- if gt $i 0 }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ $auth.name }}
  namespace: {{ $auth.namespace }}
spec:
  {{- if $auth.selector }}
  selector:
    matchLabels:
      app: {{ $auth.selector.app }}
  {{- end }}
  mtls:
    mode: {{ $auth.mtlsMode }}
---
{{- end }}
{{- end }}
