{{- range .Values.peerAuth }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  mtls:
    mode: {{ .mtlsMode }}
{{- end }}


