apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: {{ .Values.requestAuth.name }}
  namespace: {{ .Values.requestAuth.namespace }}
spec:
  jwtRules:
    - issuer: "{{ .Values.requestAuth.issuer }}"
      jwksUri: "{{ .Values.requestAuth.jwksUri }}"
      audiences:
        {{- range .Values.requestAuth.audiences }}
        - "{{ . }}"
        {{- end }}
      forwardOriginalToken: {{ .Values.requestAuth.forwardOriginalToken }}
