---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: {{ .Values.requestAuth.name }}
  namespace: {{ .Values.requestAuth.namespace }}
spec:
  jwtRules:
    - issuer: "https://{{ .Values.domain }}/auth/realms/platform"
      jwksUri: "http://keycloak.{{ .Values.namespace }}.svc.cluster.local:8080/auth/realms/platform/protocol/openid-connect/certs"
      audiences:
        {{- range .Values.requestAuth.audiences }}
        - "{{ . }}"
        {{- end }}
      forwardOriginalToken: {{ .Values.requestAuth.forwardOriginalToken }}
