{{- range .Values.virtualServices }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  {{- if .useGateway }}
  gateways:
    - {{ $.Values.gateway.namespace }}/{{ $.Values.gateway.name }}
  hosts:
    - {{ $.Values.domain }}
  {{- else }}
  hosts:
    - {{ .internalHost }}
  {{- end }}
  http:
    - route:
        {{- range .routes }}
        - destination:
            host: {{ .host }}
            port:
              number: {{ .port }}
        {{- end }}
      {{- if .timeout }}
      timeout: {{ .timeout }}
      {{- end }}
      {{- if .retries }}
      retries:
        attempts: {{ .retries.attempts }}
        retryOn: {{ .retries.retryOn }}
      {{- end }}
{{- end }}
