{{- range .Values.virtualServices }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  {{- if .gateways }}
  gateways:
    {{- range .gateways }}
    - {{ . }}
    {{- end }}
  {{- end }}
  hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  http:
    - route:
        {{- range .routes }}
        - destination:
            host: {{ .host }}
            port:
              number: {{ .port }}
        {{- end }}
      {{- if .timeout }}
      timeout: {{ .timeout }}
      {{- end }}
      {{- if .retries }}
      retries:
        attempts: {{ .retries.attempts }}
        retryOn: {{ .retries.retryOn }}
      {{- end }}
---
{{- end }}
